# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.IntegerField(verbose_name=5000)),
                ('validity', models.IntegerField(verbose_name=2)),
                ('location', models.CharField(max_length=20)),
                ('answered_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='appuser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=5000)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='expertise_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=5000)),
                ('q_detail', models.CharField(max_length=5000)),
                ('status', models.IntegerField(verbose_name=2)),
                ('ans_id', models.IntegerField(verbose_name=5000)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.questions'),
        ),
    ]
