# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161118_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_detail', models.CharField(max_length=5000)),
                ('status', models.IntegerField()),
                ('ans_id', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='answers',
            new_name='answer',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appuser',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='q_answered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='q_asked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.question'),
        ),
    ]
