# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20161118_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='location',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_detail',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
