# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20161118_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.appuser'),
            preserve_default=False,
        ),
    ]
