# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20161120_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='asked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='asked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
