# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_answer_answered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='who_answered_what',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('q_answered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='who_asked_what',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('q_asked', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='q_answered',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='q_asked',
        ),
    ]
