# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20161126_2016'),
        ('backend', '0014_remove_answer_ans_id'),
    ]

    operations = [
    ]
