# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_question_asked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='a_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='q_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='q_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
            ],
        ),
    ]
